### ISSUE TITLE
Wrong SVGO config info in readme

### ISSUE THREAD

**Issue by osvaldasvalutis** [zabute/gatsby-plugin-svgr#43]
This doesn't work:

```
plugins: {
  removeViewBox: true, // remove viewBox when possible (default)
  cleanupIDs: true,    // remove unused IDs and minify remaining IDs (default)
},
```

This works:

```
plugins: [
  { removeViewBox: true }, // remove viewBox when possible (default)
  { cleanupIDs: true },    // remove unused IDs and minify remaining IDs (default)
],
```

**Comment by coreyward** [comment]
Hey @osvaldasvalutis, thanks for the feedback. I'll try to test this in the next few days to confirm, then I can update the README accordingly.

**Comment by austin94** [comment]
```jsx
plugins: [
  { removeViewBox: true }, // remove viewBox when possible (default)
  { cleanupIDs: true },    // remove unused IDs and minify remaining IDs (default)
],
```

Is what worked for me.

**Comment by coreyward** [comment]
Thanks for confirming @austin94. @osvaldasvalutis I've updated the README to reflect this. Thank you for reporting!

**Comment by frosato-dev** [comment]
Watch out the [doc on gatsby site](https://www.gatsbyjs.org/packages/gatsby-plugin-svgr/#options) is still wrong. You may contact them and ask for update.
